#!/bin/bash

git pull origin main && cd api \
&& git pull origin master \
&& cd ../app \
&& git pull origin master\
&& cd .. \
&& docker-compose up -d --build\
&& docker-compose exec backend node_modules/.bin/sequelize db:create \
&& docker-compose exec backend node_modules/.bin/sequelize db:migrate \
&& docker-compose exec backend node_modules/.bin/sequelize db:seed:all \
&& open http://localhost